apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-app
      version: green
  template:
    metadata:
      labels:
        app: blue-green-app
        version: green
    spec:
      containers:
      - name: blue-green-app
        image: shivarawal81/blue-green-app:v3
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
