apiVersion: v1
data:
  DB_PASSWORD: UGFzc3dvcmQxMjM=
  DB_USERNAME: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2026-06-20T04:46:01Z"
  name: app-secret
  namespace: prod
  resourceVersion: "302698"
  uid: 96f6feb8-8df7-43c4-b689-f4206498d6bf
type: Opaque
